/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class github_incodelearning_jni_DemoJNI */

#ifndef _Included_github_incodelearning_jni_DemoJNI
#define _Included_github_incodelearning_jni_DemoJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     github_incodelearning_jni_DemoJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_github_incodelearning_jni_DemoJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
